import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './provider';
import { fonts } from './font';
import { Header } from './component/Header';
import { ViewTransitions } from 'next-view-transitions';
import cn from 'classnames';
import { Footer } from '@/components/Footer';
import { FloatingNavbar } from '@/components/ui/Navabar';
import { ModalProvider } from './ModalProvider';
import MobileNav from './component/MobileNav';
import { FloatingBtn } from '@/components/ui/floatingBtn';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={cn('bg-white overflow-x-hidden', fonts.rubik.variable)}
        >
          <ModalProvider />
          <Providers>
            <Header />
            <FloatingNavbar />
            {children}
            <Footer />
            <FloatingBtn />
          </Providers>
        </body>
      </html>
    </ViewTransitions>
  );
}
