import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Providers } from './provider';
import { fonts } from './font';
import { Header } from './component/Header';
import { ViewTransitions } from 'next-view-transitions';
import cn from 'classnames';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className={cn('bg-white', fonts.rubik.variable)}>
          <Providers>
            <Header />

            {children}
          </Providers>
        </body>
      </html>
    </ViewTransitions>
  );
}
